"""Create media_items table

Revision ID: 4d8d537d6def
Revises: 
Create Date: 2025-09-26 00:07:42.968759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d8d537d6def'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_id'), 'media_items', ['id'], unique=False)
    op.create_index(op.f('ix_media_items_title'), 'media_items', ['title'], unique=False)
    op.create_index(op.f('ix_media_items_tmdb_id'), 'media_items', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_items_tmdb_id'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_title'), table_name='media_items')
    op.drop_index(op.f('ix_media_items_id'), table_name='media_items')
    op.drop_table('media_items')
    # ### end Alembic commands ###
